### ISSUE TITLE
Complete the manual

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/curlInterface#1]
Basically:
* set a chapter and section title for your few functions
* add at least a brief intro section which says what curl is (and includes a link to it), and perhaps include a link to the homepage of the package
* perhaps provide an example for the download function?
* state where the file is downloaded to (current dir?)

With that done, it would almost be acceptable for depositing...

**Comment by ChrisJefferson** [comment]
At the moment, there is no download to file, only download to GAP string. I could add a direct to file option.

**Comment by fingolfin** [comment]
Another thing that would be great in the manual and/or README: some hints on how to build the package, at least for popular Linux distros and Mac OS X: 
> For Debian, Ubuntu and other Linux distributions based on them , you need to install the virtual package libcurl-dev, which is provided by one of these three packages:  libcurl4-openssl-dev, libcurl4-nss-dev, libcurl4-gnutls-dev. If in doubt, just  `sudo apt-get install libcurl4-openssl-dev`.
> For Fedora, ...
> For Mac OS X, you can install libcurl-dev via a package manager:
> * Homebrew: `brew install TODO-I-DON'T-KNOW`
> * Fink: `fink install libcurl4`
> * MacPorts: `port install curl`
> ...

**Comment by markuspf** [comment]
Fixed in #4
