### ISSUE TITLE
clang build fails

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/curlInterface#27]
As shown here:
https://travis-ci.org/gap-packages/curlInterface/builds/646315243
https://travis-ci.org/gap-packages/curlInterface/builds/646315387

It seems like this was introduced with PR #25, which is weird, because the pull request tests passed.

@fingolfin: any ideas?

**Comment by ChrisJefferson** [comment]
I hit the rebuild buttons, and they seem to have cleared up, so I guess it was just a travis hiccup.
